// Absentees Actions
export const FETCH_ABSENTEES = "FETCH_ABSENTEES";
export const FETCH_ABSENTEES_SUCCESS = "FETCH_ABSENTEES_SUCCESS";
export const FETCH_ABSENTEES_ERROR = "FETCH_ABSENTEES_SUCCESS";

//Absentees with Pagination
export const FETCH_ABSENTEES_PAGINATION = "FETCH_ABSENTEES_PAGINATION";

// Absentees Filter Actions
export const FILTER_BY_TYPE = "FILTER_BY_TYPE";
export const FILTER_BY_DATE = "FILTER_BY_TYPE";

// Members Action
export const FETCH_MEMBERS = "FETCH_MEMBERS";
export const FETCH_MEMBERS_SUCCESS = "FETCH_MEMBERS_SUCCESS";
export const FETCH_MEMBERS_ERROR = "FETCH_MEMBERS_SUCCESS";
