// Absentees Actions
export const FETCH_ABSENTEES = "FETCH_ABSENTEES";
export const FETCH_ABSENTEES_SUCCESS = "FETCH_ABSENTEES_SUCCESS";
export const FETCH_ABSENTEES_ERROR = "FETCH_ABSENTEES_SUCCESS";

// Members Action
export const FETCH_MEMBERS = "FETCH_MEMBERS";
export const FETCH_MEMBERS_SUCCESS = "FETCH_MEMBERS_SUCCESS";
export const FETCH_MEMBERS_ERROR = "FETCH_MEMBERS_SUCCESS";
