// Absences Actions
export const FETCH_ABSENCES = "FETCH_ABSENCES";
export const FETCH_ABSENCES_SUCCESS = "FETCH_ABSENCES_SUCCESS";
export const FETCH_ABSENCES_ERROR = "FETCH_ABSENCES_SUCCESS";

//Absences with Pagination
export const FETCH_ABSENCES_PAGINATION = "FETCH_ABSENCES_PAGINATION";

// Absences Filter Actions
export const FILTER_BY_TYPE = "FILTER_BY_TYPE";
export const FILTER_BY_DATE = "FILTER_BY_TYPE";

// Members Action
export const FETCH_MEMBERS = "FETCH_MEMBERS";
export const FETCH_MEMBERS_SUCCESS = "FETCH_MEMBERS_SUCCESS";
export const FETCH_MEMBERS_ERROR = "FETCH_MEMBERS_SUCCESS";
